input = style citation macro*

<start> = <'{'>
<stop> = <'}'>

style = <'style'> start style-statement+ stop

style-statement =
    ('title' str)
|   ('author' str str?)

citation = <'citation'> start statement+ stop

macro = <'macro'> #'[a-z0-9]+' start statement+ stop

statement = #'".*?"'
<str> = #'".*?"'

<end> = <'end'>