style = info macro* citation

info =
    <'info'> <'{'>
        info-statement+
    <'}'>

info-statement =
    ('title' str)
|   ('author' str str?)

citation =
    <'citation'> <'{'>
        statement+
    <'}'>

macro =
    <'macro'> #'[a-z0-9]+' <'{'>
        statement+
    <'}'>

statement = #'".*?"'
<str> = #'".*?"'
