program = program-statement+

<program-statement> =
    about
|   citation

about =
    <'about'> <'{'>
        meta-statement+
    <'}'>

<person-detail-statement> = email
                          | url

meta-statement = id
               | issn
               | eissn
               | issnl
               | title
               | title-short
               | summary
               | published
               | updated
               | citation-format
               | field-statement
               | license
               | url
               | documentation
               | template
               | person-statement

id = <'id'> str
url = <'url'> str lang?
template = <'template'> str lang?
documentation = <'documentation'> str lang?
email = <'email'> str
author = (<'author'> str) | (<'author'> str <'{'> person-detail-statement+ <'}'>)
contributor = (<'contributor'> str) | (<'contributor'> str <'{'> person-detail-statement+ <'}'>)
person-statement = author | contributor
issn = <'issn'> str
eissn = <'eissn'> str
issnl = <'issnl'> str
citation-format = <'citation-format'> str
field-statement = <'field'> str
summary = <'summary'> str lang?
published = <'published'> str
updated = <'updated'> str
title = <'title'> str lang?
title-short = <'title-short'> str lang?
license = <'license'> str lang?

prefix = <'--prefix'> str
suffix = <'--suffix'> str
delimiter = <'--delimiter'> str
font-style = <'--'> ('italique' | 'oblique')
font-variant = <'--'> 'small-caps'
font-weight= <'--'> ('bold' | 'light-bold')
text-decoration = <'--'> 'underline'
vertical-align = <'--'> ('sup' | 'sub')
display = <'--'> ('left' | 'right' | 'indent')

<modifier> = prefix
           | suffix
           | delimiter
           | font-style
           | font-variant
           | font-weight
           | text-decoration
           | vertical-align
           | display

modifiers = modifier+

print = print-text
      | print-num
      | print-term
      | print-date

print-text = <'print'> modifiers? var-txt
print-num = <'print'> modifiers? var-num
print-term = <'print'> modifiers? var-term
print-date = <'print'> modifiers? var-date

var-date = <'$'>'accessed'
         | <'$'>'container'
         | <'$'>'event-date'
         | <'$'>'issued'
         | <'$'>'original-date'
         | <'$'>'submitted'

var-txt = <'$'>'title'

var-num = <'$'>'chapter-number'
        | <'$'>'collection-number'
        | <'$'>'edition'
        | <'$'>'issue'
        | <'$'>'number'
        | <'$'>'number-of-pages'
        | <'$'>'number-of-volumes'
        | <'$'>'volume'

var-term = <'&'>'book'
         | <'&'>'chapter'
         | <'&'>'column'
         | <'&'>'figure'
         | <'&'>'folio'
         | <'&'>'issue'
         | <'&'>'line'
         | <'&'>'note'
         | <'&'>'opus'
         | <'&'>'page'
         | <'&'>'paragraph'
         | <'&'>'part'
         | <'&'>'section'
         | <'&'>'sub verbo'
         | <'&'>'verse'
         | <'&'>'volume'
         | <'&'>'month-01'
         | <'&'>'month-02'
         | <'&'>'month-03'
         | <'&'>'month-04'
         | <'&'>'month-05'
         | <'&'>'month-06'
         | <'&'>'month-07'
         | <'&'>'month-08'
         | <'&'>'month-09'
         | <'&'>'month-10'
         | <'&'>'month-11'
         | <'&'>'month-12'
         | <'&'>'ordinal'
         | <'&'>'ordinal-00'
         | <'&'>'ordinal-01'
         | <'&'>'ordinal-02'
         | <'&'>'ordinal-03'
         | <'&'>'ordinal-04'
         | <'&'>'ordinal-05'
         | <'&'>'ordinal-06'
         | <'&'>'ordinal-07'
         | <'&'>'ordinal-08'
         | <'&'>'ordinal-09'
         | <'&'>'ordinal-10'
         | <'&'>'ordinal-11'
         | <'&'>'ordinal-12'
         | <'&'>'ordinal-13'
         | <'&'>'ordinal-14'
         | <'&'>'ordinal-15'
         | <'&'>'ordinal-16'
         | <'&'>'ordinal-17'
         | <'&'>'ordinal-18'
         | <'&'>'ordinal-19'
         | <'&'>'ordinal-20'
         | <'&'>'ordinal-21'
         | <'&'>'ordinal-22'
         | <'&'>'ordinal-23'
         | <'&'>'ordinal-24'
         | <'&'>'ordinal-25'
         | <'&'>'ordinal-26'
         | <'&'>'ordinal-27'
         | <'&'>'ordinal-28'
         | <'&'>'ordinal-29'
         | <'&'>'ordinal-30'
         | <'&'>'ordinal-31'
         | <'&'>'ordinal-32'
         | <'&'>'ordinal-33'
         | <'&'>'ordinal-34'
         | <'&'>'ordinal-35'
         | <'&'>'ordinal-36'
         | <'&'>'ordinal-37'
         | <'&'>'ordinal-38'
         | <'&'>'ordinal-39'
         | <'&'>'ordinal-40'
         | <'&'>'ordinal-41'
         | <'&'>'ordinal-42'
         | <'&'>'ordinal-43'
         | <'&'>'ordinal-44'
         | <'&'>'ordinal-45'
         | <'&'>'ordinal-46'
         | <'&'>'ordinal-47'
         | <'&'>'ordinal-48'
         | <'&'>'ordinal-49'
         | <'&'>'ordinal-50'
         | <'&'>'ordinal-51'
         | <'&'>'ordinal-52'
         | <'&'>'ordinal-53'
         | <'&'>'ordinal-54'
         | <'&'>'ordinal-55'
         | <'&'>'ordinal-56'
         | <'&'>'ordinal-57'
         | <'&'>'ordinal-58'
         | <'&'>'ordinal-59'
         | <'&'>'ordinal-60'
         | <'&'>'ordinal-61'
         | <'&'>'ordinal-62'
         | <'&'>'ordinal-63'
         | <'&'>'ordinal-64'
         | <'&'>'ordinal-65'
         | <'&'>'ordinal-66'
         | <'&'>'ordinal-67'
         | <'&'>'ordinal-68'
         | <'&'>'ordinal-69'
         | <'&'>'ordinal-70'
         | <'&'>'ordinal-71'
         | <'&'>'ordinal-72'
         | <'&'>'ordinal-73'
         | <'&'>'ordinal-74'
         | <'&'>'ordinal-75'
         | <'&'>'ordinal-76'
         | <'&'>'ordinal-77'
         | <'&'>'ordinal-78'
         | <'&'>'ordinal-79'
         | <'&'>'ordinal-80'
         | <'&'>'ordinal-81'
         | <'&'>'ordinal-82'
         | <'&'>'ordinal-83'
         | <'&'>'ordinal-84'
         | <'&'>'ordinal-85'
         | <'&'>'ordinal-86'
         | <'&'>'ordinal-87'
         | <'&'>'ordinal-88'
         | <'&'>'ordinal-89'
         | <'&'>'ordinal-90'
         | <'&'>'ordinal-91'
         | <'&'>'ordinal-92'
         | <'&'>'ordinal-93'
         | <'&'>'ordinal-94'
         | <'&'>'ordinal-95'
         | <'&'>'ordinal-96'
         | <'&'>'ordinal-97'
         | <'&'>'ordinal-98'
         | <'&'>'ordinal-99'
         | <'&'>'long-ordinal-01'
         | <'&'>'long-ordinal-02'
         | <'&'>'long-ordinal-03'
         | <'&'>'long-ordinal-04'
         | <'&'>'long-ordinal-05'
         | <'&'>'long-ordinal-06'
         | <'&'>'long-ordinal-07'
         | <'&'>'long-ordinal-08'
         | <'&'>'long-ordinal-09'
         | <'&'>'long-ordinal-10'
         | <'&'>'open-quote'
         | <'&'>'close-quote'
         | <'&'>'open-inner-quote'
         | <'&'>'close-inner-quote'
         | <'&'>'author'
         | <'&'>'collection-editor'
         | <'&'>'composer'
         | <'&'>'container-author'
         | <'&'>'director'
         | <'&'>'editor'
         | <'&'>'editorial-director'
         | <'&'>'editortranslator'
         | <'&'>'illustrator'
         | <'&'>'interviewer'
         | <'&'>'original-author'
         | <'&'>'recipient'
         | <'&'>'reviewed-author'
         | <'&'>'translator'
         | <'&'>'season-01'
         | <'&'>'season-02'
         | <'&'>'season-03'
         | <'&'>'season-04'
         | <'&'>'accessed'
         | <'&'>'ad'
         | <'&'>'and'
         | <'&'>'and others'
         | <'&'>'anonymous'
         | <'&'>'at'
         | <'&'>'available at'
         | <'&'>'bc'
         | <'&'>'by'
         | <'&'>'circa'
         | <'&'>'cited'
         | <'&'>'edition'
         | <'&'>'et-al'
         | <'&'>'forthcoming'
         | <'&'>'from'
         | <'&'>'ibid'
         | <'&'>'in'
         | <'&'>'in press'
         | <'&'>'internet'
         | <'&'>'interview'
         | <'&'>'letter'
         | <'&'>'no date'
         | <'&'>'online'
         | <'&'>'presented at'
         | <'&'>'reference'
         | <'&'>'retrieved'
         | <'&'>'scale'
         | <'&'>'version'

<lang> = <'('> #'[a-zA-Z-]+' <')'>
str = <'"'> chr* <'"'>
<chr> = #'[^"]'

citation =
    <'citation'> <'{'>
        modifiers?
        print*
    <'}'>