name: Continuous Integration
on: push

jobs:
  test:
    name: Running Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run --rm --mount type=bind,src=$GITHUB_WORKSPACE,dst=/workspaces/fahrenheit -w /workspaces/fahrenheit clojure:lein lein test
